AWSTemplateFormatVersion: "2010-09-09"
Description: Cameron's Testing Stack - SpotFleet
Resources:
  MyFirstSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MyFirstSG
      GroupDescription: It is not my first or last SecurityGroup
      SecurityGroupIngress:
        - CidrIP: "0.0.0.0/0"
          Description: It works
          FromPort: "22"
          IpProtocol: tcp
          ToPort: "22"

        - CidrIP: "0.0.0.0/0"
          Description: It works
          FromPort: "8080"
          IpProtocol: tcp
          ToPort: "8080"

        - CidrIP: "0.0.0.0/0"
          Description: It works
          FromPort: "4000"
          IpProtocol: tcp
          ToPort: "4000"
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06d09f028154f2ffa
      InstanceType: t2.micro
      KeyName: Op-aws-Test
      SecurityGroup: MyFirstSG
    DependsOn: MyFirstSG
  MySpotFleet:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        AllocationStrategy: lowestPrice
        InstanceInterruptBehavior: stop
        LaunchSpecifications:
          ImageId: ami-0799ad445b5727125
          InstanceType: t2.micro
          SpotPrice: ".0035"
          WeightedCapacity: "1"
        TargetCapacity: "2"
    DependsOn: MyFirstSG
